POST http://localhost:5000/api/users
Content-Type: application/json

{
    "email": "test1@test.com",
    "name": "Test",
    "password": "test123",
    "role": "ADMIN"
}

###
PUT http://localhost:5000/api/users/2
Content-Type: application/json

{
    "email": "duarr@test.com",
    "name": "Testtt",
    "password": "test1234",
    "role": "STAFF_PRODUKSI"
}

###
DELETE http://localhost:5000/api/users/1

###
POST http://localhost:5000/api/inventaris
Content-Type: application/json

{
    "nama_barang": "Kain",
    "quantity": 20,
    "satuan": "Meter"
}


###
GET http://localhost:5000/api/users

###
GET http://localhost:5000/api/users?name=Test

###
GET http://localhost:5000/api/inventaris/1

###
GET http://localhost:5000/api/inventaris/search?nama_barang=Gerinda

###
POST http://localhost:5000/api/materials
Content-Type: application/json

{
    "kode_material": "M003",
    "nama_material": "Akrilik",
    "satuan": "Lembar"
}

###
GET http://localhost:5000/api/materials

###
POST http://localhost:5000/api/movements/in
Content-Type: application/json

{
    "material_id": 4,
    "quantity": 5
}

###
POST http://localhost:5000/api/movements/out
Content-Type: application/json

{
    "material_id": 1,
    "quantity": 50
}

###
GET http://localhost:5000/api/movements

###
POST http://localhost:5000/api/orders
Content-Type: application/json

{
    "nama_pemesan": "PT.ABCDE",
    "kode_pesanan": "P002",
    "estimatedTime": "2021-12-31T00:00:00.000Z",
    "products": [
        {
            "kode_produk": "PROD-3",
            "nama_produk": "Product 3",
            "deskripsi": "Description of product 3",
            "productMaterials": [
                { "material_id": 1, "quantity": 1 },
                { "material_id": 4, "quantity": 1 }
            ]
        },
        {
            "kode_produk": "PROD-4",
            "nama_produk": "Product 4",
            "deskripsi": "Description of product 4",
            "productMaterials": [
                { "material_id": 1, "quantity": 1 },
                { "material_id": 4, "quantity": 1 }
            ]
        }
    ]
}


###
POST http://localhost:5000/api/products
Content-Type: application/json

{
    "kode_produk": "PROD-1",
    "nama_produk": "Product 1",
    "deskripsi": "Ini adalah deskripsi dari product 1",
    "materials": [
        { "material_id": 1,  "quantity": 3 },
        { "material_id": 2, "quantity": 100 }
    ]
}

###
GET http://localhost:5000/api/products


###
GET http://localhost:5000/api/orders